# Generated by Django 5.2.4 on 2025-08-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="comment",
        ),
    ]
