# Generated by Django 5.2.4 on 2025-07-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("size", models.CharField(max_length=3)),
                ("uploaded_image", models.ImageField(blank=True, upload_to="images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Bottom",
        ),
        migrations.DeleteModel(
            name="Main",
        ),
        migrations.DeleteModel(
            name="Outer",
        ),
        migrations.DeleteModel(
            name="Shoes",
        ),
        migrations.DeleteModel(
            name="Top",
        ),
    ]
