# Generated by Django 5.2.4 on 2025-07-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_post_delete_bottom_delete_main_delete_outer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.CharField(null=True),
        ),
    ]
