# Generated by Django 5.2.5 on 2025-08-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="uploaded_image",
        ),
    ]
